# Generated by Django 5.0.1 on 2024-02-10 15:15

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1, verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='collaborators',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborate_on', to=settings.AUTH_USER_MODEL),
        ),
    ]
