# Generated by Django 5.0.1 on 2024-10-29 10:36

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='body',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
